// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace test_wd_bots.migrations_klaytn.hash
{
    [DbContext(typeof(Transaction_DB_klaytn))]
    [Migration("20220804042840_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("eight_Transaction_Logs", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockNumber")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("data")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("logIndex")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionIndex")
                        .HasColumnType("varchar(1024)");

                    b.HasKey("id");

                    b.ToTable("eight_Transaction_Logs");
                });

            modelBuilder.Entity("five_Transaction_Logs", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockNumber")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("data")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("logIndex")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionIndex")
                        .HasColumnType("varchar(1024)");

                    b.HasKey("id");

                    b.ToTable("five_Transaction_Logs");
                });

            modelBuilder.Entity("four_Transaction_Logs", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockNumber")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("data")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("logIndex")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionIndex")
                        .HasColumnType("varchar(1024)");

                    b.HasKey("id");

                    b.ToTable("four_Transaction_Logs");
                });

            modelBuilder.Entity("one_Transaction_Logs", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockNumber")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("data")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("logIndex")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionIndex")
                        .HasColumnType("varchar(1024)");

                    b.HasKey("id");

                    b.ToTable("one_Transaction_Logs");
                });

            modelBuilder.Entity("seven_Transaction_Logs", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockNumber")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("data")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("logIndex")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionIndex")
                        .HasColumnType("varchar(1024)");

                    b.HasKey("id");

                    b.ToTable("seven_Transaction_Logs");
                });

            modelBuilder.Entity("six_Transaction_Logs", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockNumber")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("data")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("logIndex")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionIndex")
                        .HasColumnType("varchar(1024)");

                    b.HasKey("id");

                    b.ToTable("six_Transaction_Logs");
                });

            modelBuilder.Entity("three_Transaction_Logs", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockNumber")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("data")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("logIndex")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionIndex")
                        .HasColumnType("varchar(1024)");

                    b.HasKey("id");

                    b.ToTable("three_Transaction_Logs");
                });

            modelBuilder.Entity("two_Transaction_Logs", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("address")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("blockNumber")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("data")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("logIndex")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionHash")
                        .HasColumnType("varchar(1024)");

                    b.Property<string>("transactionIndex")
                        .HasColumnType("varchar(1024)");

                    b.HasKey("id");

                    b.ToTable("two_Transaction_Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
